apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
  annotations:
        k8s.v1.cni.cncf.io/networks: {{ .Values.macvlan.name }}
  namespace: {{ .Values.macvlan.namespace }}
spec:
  containers:
<<<<<<< HEAD
      name: {{ .Values.deployment.name }}
      image: "{{ .Values.deployment.image }}:{{ .Values.deployment.tag }}"
      args: [
        register-run,
        config: {{ .Values.deployment.args.config}},
        -A,
        --ssl-no-check,
        ncc-host: {{ index .Values.deployment "ncc-host" }},
        account: {{ .Values.deployment.account }},
        email: {{ .Values.deployment.email }},
        password: {{ .Values.deployment.password }},
        name: {{ .Values.deployment.name }} ]
=======
    - name: {{ .Values.deployment.name }}
      image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
      args:
        - ncc-host: {{ .Values.deployment.ncc-host }}
          account: {{ .Values.deployment.account }}
          email: {{ .Values.deployment.email }}
          password: {{ .Values.deployment.password }}
          name: {{ .Values.deployment.name }}
>>>>>>> f9be8384674ee8f64095b9205f2dd94b081a524f
      command:
            - /paa-test-agent-application/paa-test-agent-application
      env:
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      ports:
      securityContext:
        privileged: true
      volumeMounts:
        - name: test1
          mountPath: /config
        - name: test2
          mountPath: /var/run/netns
  volumes:
    - name: test1
      persistentVolumeClaim:
        claimName: {{ .Values.deployment.name }}-pvc1
    - name: test2
      persistentVolumeClaim:
        claimName: {{ .Values.deployment.name }}-pvc2
