apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: test1
  storageClassName: nfs-storage
