apiVersion: v1
kind: PersistentVolume
metadata:
  name: test1
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /test1
    server: 192.168.22.111
  persistentVolumeReclaimPolicy: Retain

