apiVersion: v1
kind: PersistentVolume
metadata:
  name: test2
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /test2
    server: 192.168.22.111
  persistentVolumeReclaimPolicy: Retain

