apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: test2
  storageClassName: nfs-storage

