deployment:
  name: agent1
  labels: 
   app: agent-1
   image: netrounds/test-agent-application
   tag: latest
   args:
     config: /config/agent.conf
     ncchost: 192.168.5.2
     account: verizon
     email: anand.shanmuganathan@one.verizon.com
     password: January123$
     name: TA_Cont6

macvlan:
  name: test-network-106
  namespace: pradeep
  ipamConfig:
    addresses:
      address: 192.168.5.6/2
      gateway: 192.168.5.2
    routes:
      destination: 0.0.0.0/0
      gateway: 192.168.5.2
